In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/lines.csv")

In [3]:
df[(df["LINE"] == "319/1")].sort_values(by = ["DEPDT","DEPTM"]).head(50)

,ORGN,DSTN,FLTNUM,DEPDT,ARRDT,DEPTM,ARRTM,AC_TYPE,AIRCRAFT_ID,LINE
0,HEL,GZP,1933,20220401,20220401,03:30,07:15,319,1,319/1
1,GZP,HEL,1934,20220401,20220401,08:05,11:55,319,1,319/1
2,HEL,ARN,813,20220401,20220401,12:55,13:55,319,1,319/1
3,ARN,HEL,814,20220401,20220401,14:35,15:35,319,1,319/1
4,HEL,LHR,1339,20220401,20220401,16:30,19:40,319,1,319/1
5,LHR,HEL,1340,20220402,20220402,06:30,09:20,319,1,319/1
6,HEL,ARN,807,20220402,20220402,10:00,11:00,319,1,319/1
7,ARN,HEL,808,20220402,20220402,11:40,12:40,319,1,319/1
8,HEL,BUD,1255,20220402,20220402,13:45,16:10,319,1,319/1
9,BUD,HEL,1256,20220402,20220402,17:00,19:20,319,1,319/1
10,HEL,BER,1431,20220403,20220403,04:25,06:25,319,1,319/1
11,BER,HEL,1432,20220403,20220403,07:15,09:05,319,1,319/1
12,HEL,RVN,533,20220403,20220403,09:20,10:35,319,1,319/1
13,RVN,HEL,534,20220403,20220403,11:15,12:30,319,1,319/1
14,HEL,KUO,369,20220403,20220403,13:30,14:30,319,1,319/1
15,KUO,HEL,370,20220403,20220403,14:55,15:55,319,1,319/1
16,HEL,KAO,487,20220403,20220403,16:25,18:05,319,1,319/1
17,KAO,HEL,488,20220403,20220403,18:30,20:10,319,1,319/1
18,HEL,OUL,435,20220404,20220404,05:05,06:10,319,1,319/1
19,OUL,HEL,436,20220404,20220404,06:50,07:50,319,1,319/1
20,HEL,WAW,1143,20220404,20220404,08:35,10:15,319,1,319/1
21,WAW,HEL,1144,20220404,20220404,11:00,12:40,319,1,319/1
22,HEL,TLL,1023,20220404,20220404,13:25,14:00,319,1,319/1
23,TLL,HEL,1024,20220404,20220404,14:25,15:00,319,1,319/1
24,HEL,GDN,1173,20220404,20220404,15:30,17:30,319,1,319/1
25,GDN,HEL,1174,20220404,20220404,18:05,20:05,319,1,319/1
26,HEL,OUL,433,20220405,20220405,04:30,05:30,319,1,319/1
27,OUL,HEL,434,20220405,20220405,06:10,07:10,319,1,319/1
28,HEL,VNO,1107,20220405,20220405,08:30,10:10,319,1,319/1
29,VNO,HEL,1108,20220405,20220405,10:40,12:30,319,1,319/1
30,HEL,IVL,605,20220405,20220405,13:40,15:20,319,1,319/1
31,IVL,HEL,606,20220405,20220405,16:00,17:30,319,1,319/1
32,HEL,RVN,537,20220405,20220405,18:35,19:50,319,1,319/1
33,RVN,HEL,538,20220406,20220406,02:30,03:45,319,1,319/1
34,HEL,OUL,435,20220406,20220406,05:05,06:10,319,1,319/1
35,OUL,HEL,436,20220406,20220406,06:50,07:50,319,1,319/1
36,HEL,SVO,715,20220406,20220406,08:10,09:50,319,1,319/1
37,SVO,HEL,716,20220406,20220406,10:35,12:20,319,1,319/1
38,HEL,ARN,813,20220406,20220406,12:55,13:55,319,1,319/1
39,ARN,HEL,814,20220406,20220406,14:35,15:35,319,1,319/1
40,HEL,OUL,445,20220406,20220406,17:25,18:25,319,1,319/1
41,OUL,HEL,446,20220406,20220406,19:10,20:10,319,1,319/1
42,HEL,GOT,861,20220407,20220407,04:30,06:00,319,1,319/1
43,GOT,HEL,862,20220407,20220407,06:40,08:00,319,1,319/1
44,HEL,SVO,715,20220407,20220407,08:10,09:50,319,1,319/1
45,SVO,HEL,716,20220407,20220407,10:35,12:20,319,1,319/1
46,HEL,RVN,535,20220407,20220407,13:20,14:35,319,1,319/1
47,RVN,HEL,536,20220407,20220407,15:15,16:30,319,1,319/1
48,HEL,RVN,537,20220407,20220407,18:35,19:50,319,1,319/1
49,RVN,HEL,538,20220408,20220408,02:30,03:45,319,1,319/1

In [20]:
df[((df["ORGN"] == "WAW") | (df["DSTN"] == "WAW")) & (df["DEPDT"] == 20220403)].head(5)

Empty DataFrame
Columns: [ORGN, DSTN, FLTNUM, DEPDT, ARRDT, DEPTM, ARRTM, AC_TYPE, AIRCRAFT_ID, LINE]
Index: []