In [5]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [6]:
df = pd.read_csv("s3://ay-rmp-home/nrm/bif/2023/05/INV_20230522.csv.gz")

In [7]:
df.head(5)

,CC,FLTNUM,DEPDT,DEPTM,DEPDT_UTC,DEPTM_UTC,ARRDT,ARRTM,ARRDT_UTC,ARRTM_UTC,ORGN,DSTN,DAYSPRIOR,AIRCRAFT_TYPE,CABIN,CAPS,CAPA,CAPO,CAPE,BKC,ETB,RC,EGS,AMR,RCR,ESB,SRC_DATE
0,AY,9,20230518,1600,20230518,1400,20230518,1725,20230518,2325,HEL,ORD,-4,33S,J,28,28,28,28,9,13,RY,0,100.0,0.0,9.0,20230522
1,AY,9,20230518,1600,20230518,1400,20230518,1725,20230518,2325,HEL,ORD,-4,33S,W,21,38,21,38,12,11,RY,0,100.0,0.0,12.0,20230522
2,AY,9,20230518,1600,20230518,1400,20230518,1725,20230518,2325,HEL,ORD,-4,33S,Y,230,254,230,254,137,143,RY,0,100.0,0.0,137.0,20230522
3,AY,10,20230518,2130,20230519,330,20230519,1415,20230519,1215,ORD,HEL,-4,33S,J,28,28,28,28,29,28,RY,0,100.0,0.0,29.0,20230522
4,AY,10,20230518,2130,20230519,330,20230519,1415,20230519,1215,ORD,HEL,-4,33S,W,21,20,21,20,18,21,RY,0,100.0,0.0,18.0,20230522

In [9]:
df[
    (df["ORGN"] == "HEL") & 
    (df["DSTN"] == "BGO") &
    (df["DEPDT"] == 20230522)
]

,CC,FLTNUM,DEPDT,DEPTM,DEPDT_UTC,DEPTM_UTC,ARRDT,ARRTM,ARRDT_UTC,ARRTM_UTC,ORGN,DSTN,DAYSPRIOR,AIRCRAFT_TYPE,CABIN,CAPS,CAPA,CAPO,CAPE,BKC,ETB,RC,EGS,AMR,RCR,ESB,SRC_DATE
20723,AY,941,20230522,1605,20230522,1405,20230522,1720,20230522,1620,HEL,BGO,0,WF8,J,6,5,6,5,1,1,RY,0,100.0,0.0,1.000,20230522
20724,AY,941,20230522,1605,20230522,1405,20230522,1720,20230522,1620,HEL,BGO,0,WF8,Y,72,76,72,76,73,71,RY,0,100.0,4.3,69.861,20230522
20734,AY,943,20230522,710,20230522,510,20230522,840,20230522,740,HEL,BGO,0,A70,Y,70,70,70,70,67,64,RY,0,100.0,4.3,64.119,20230522