In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("s3://ay-emr-job/nrm/fdc/2024/05/20/fdc_20240520_20240716.csv.gz", low_memory=False)

In [7]:
df[(df["BASE_OD_ORGN"] == "JFK") & (df["BASE_OD_DSTN"] == "TLL") & (df["POS"] == "US")].head(10)

,GEO_OD_TS_KEY,BASE_OD_ORGN,BASE_OD_DSTN,BASE_OD_VIA,BASE_OD_ORGN_COUNTRY,BASE_OD_ORGN_REGION,BASE_OD_DSTN_COUNTRY,BASE_OD_DSTN_REGION,BASE_OPR_CC,BASE_OPR_FLTNUM,...,BC,FF,TP,SMPWA,AMPWA,SRD,ARD,SFD,AFD,SRC_DATE
350550,JFKHEL2024071620240717AY0016HELTLL202407182024...,JFK,TLL,HEL,US,NAMER,EE,EUROPE,AY-AY,16-1011,...,A,NaN,B,0.0,0.0,0.0,0.0,0.0,0.0,20240513
350551,JFKHEL2024071620240717AY0016HELTLL202407182024...,JFK,TLL,HEL,US,NAMER,EE,EUROPE,AY-AY,16-1011,...,A,NaN,L,0.0,0.0,0.0,0.0,0.0,0.0,20240513
350552,JFKHEL2024071620240717AY0016HELTLL202407182024...,JFK,TLL,HEL,US,NAMER,EE,EUROPE,AY-AY,16-1011,...,J,UEJ,B,0.0,0.0,0.0,0.0,0.0,0.0,20240513
350553,JFKHEL2024071620240717AY0016HELTLL202407182024...,JFK,TLL,HEL,US,NAMER,EE,EUROPE,AY-AY,16-1011,...,J,UEJ,L,0.0,0.0,0.0,0.0,0.0,0.0,20240513
350554,JFKHEL2024071620240717AY0016HELTLL202407182024...,JFK,TLL,HEL,US,NAMER,EE,EUROPE,AY-AY,16-1011,...,C,UEJ,B,0.0,0.0,0.0,0.0,0.0,0.0,20240513
350555,JFKHEL2024071620240717AY0016HELTLL202407182024...,JFK,TLL,HEL,US,NAMER,EE,EUROPE,AY-AY,16-1011,...,C,UEJ,L,0.0,0.0,0.0,0.0,0.0,0.0,20240513
350556,JFKHEL2024071620240717AY0016HELTLL202407182024...,JFK,TLL,HEL,US,NAMER,EE,EUROPE,AY-AY,16-1011,...,D,UEJ,B,0.0,0.0,0.0,0.0,0.0,0.0,20240513
350557,JFKHEL2024071620240717AY0016HELTLL202407182024...,JFK,TLL,HEL,US,NAMER,EE,EUROPE,AY-AY,16-1011,...,D,UEJ,L,0.0,0.0,0.0,0.0,0.0,0.0,20240513
350558,JFKHEL2024071620240717AY0016HELTLL202407182024...,JFK,TLL,HEL,US,NAMER,EE,EUROPE,AY-AY,16-1011,...,R,UEJ,B,0.0,0.0,0.0,0.0,0.0,0.0,20240513
350559,JFKHEL2024071620240717AY0016HELTLL202407182024...,JFK,TLL,HEL,US,NAMER,EE,EUROPE,AY-AY,16-1011,...,R,UEJ,L,0.0,0.0,0.0,0.0,0.0,0.0,20240513

In [8]:
df = pd.read_csv("s3://ay-emr-job/nrm/cf/2024/05/20/cf_20240520_20240716.csv.gz", low_memory=False)

In [9]:
df[(df["BASE_OD_ORGN"] == "JFK") & (df["BASE_OD_DSTN"] == "TLL") & (df["POS"] == "US")].head(10)

Empty DataFrame
Columns: [GEO_OD_TS_KEY, BASE_OD_ORGN, BASE_OD_DSTN, BASE_OD_VIA, BASE_OD_ORGN_COUNTRY, BASE_OD_ORGN_REGION, BASE_OD_DSTN_COUNTRY, BASE_OD_DSTN_REGION, BASE_OPR_CC, BASE_OPR_FLTNUM, BASE_MKT_CC, BASE_MKT_FLTNUM, BASE_OD_DEPT_DATE, BASE_SEG_DEP_DATE, BASE_SEG_ARR_DATE, GEO_ORGN, GEO_DSTN, PREV_VIA, PREV_OPR_CC, PREV_OPR_FLTNUM, PREV_MKT_CC, PREV_MKT_FLTNUM, PREV_SEG_DEP_DATE, PREV_SEG_ARR_DATE, NEXT_VIA, NEXT_OPR_CC, NEXT_OPR_FLTNUM, NEXT_MKT_CC, NEXT_MKT_FLTNUM, NEXT_SEG_DEP_DATE, NEXT_SEG_ARR_DATE, POS, BC, FF, TP, MP, D, LPS, SRC_DATE]
Index: []

[0 rows x 39 columns]